import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import { Toaster } from "@/components/user/ui/Sonner";
import AOSInit from "./component/AOSInit";
import AuthProvider from "@/components/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Everwood collection",
  description: "Generated by create next app",
  icons: {
    icon: "/Favicon/Favicon.png",
  },
};
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Toaster />
        <AOSInit />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
